version: "3.8"

services:
  skyoffice-client:
    container_name: skyoffice-client
    image: skyoffice-client
    labels:
      - traefik.http.routers.testClient.rule=Host(`test.honbu.cloud`)
      - traefik.http.routers.testClient.tls=true
      - traefik.http.routers.testClient.tls.certresolver=lets-encrypt
      - traefik.port=3000
    networks:
      - web
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
networks:
  web:
    external: true